# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Ongoing Research
    url: '#projects'
    weight: 10
  - name: Team
    url: '#people'
    weight: 20
  - name: Core Skills
    url: '#skills'
    weight: 30
  - name: Publications
    url: '#publications'
    weight: 40
  - name: Posts
    url: '#posts'
    weight: 50
  - name: Funding
    url: '#funding'
    weight: 60
  - name: Gallery
    url: '#gallery'
    weight: 70
  - name: Contact
    url: '#contact'
    weight: 80
