# Font style metadata
name = "Noto"

# Optional Google font URL
google_fonts = "family=Noto+Sans+KR:wght@500&display=swap"

# Font families
heading_font = "Noto Sans KR"
body_font = "Noto Sans KR"
nav_font = "Noto Sans KR"
mono_font = "Noto Sans KR"
